// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1056:Uri properties should not be strings", Justification = "<Pending>", Scope = "member", Target = "~P:SportBox7.Data.Models.Article.ImageUrl")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1056:Uri properties should not be strings", Justification = "<Pending>", Scope = "member", Target = "~P:SportBox7.Data.Models.ArticleCeoData.SeoUrl")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1056:Uri properties should not be strings", Justification = "<Pending>", Scope = "member", Target = "~P:SportBox7.Data.Models.ArticleSeoData.SeoUrl")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1056:Uri properties should not be strings", Justification = "<Pending>", Scope = "member", Target = "~P:SportBox7.Areas.Editors.ViewModels.AddArticleForReviewViewModel.SourceURL")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1056:Uri properties should not be strings", Justification = "<Pending>", Scope = "member", Target = "~P:SportBox7.Areas.Editors.ViewModels.AddArticleForReviewViewModel.ImageUrl")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1056:Uri properties should not be strings", Justification = "<Pending>", Scope = "member", Target = "~P:SportBox7.Areas.Editors.ViewModels.AddArticleForReviewViewModel.SeoUrl")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:SportBox7.Data.Seed.DBInitializer.SeedRoles(Microsoft.AspNetCore.Identity.RoleManager{Microsoft.AspNetCore.Identity.IdentityRole})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:SportBox7.Areas.Editors.Services.Interfaces.EditorService.AddArticleForReview(SportBox7.Areas.Editors.ViewModels.AddArticleForReviewViewModel)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:SportBox7.Areas.Editors.Controllers.AuthorsController.AddNewDraft(SportBox7.Areas.Editors.ViewModels.AddArticleViewModel)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:SportBox7.Areas.Editors.Controllers.AuthorsController.EditDraft(SportBox7.Areas.Editors.ViewModels.Content.EditArticleViewModel)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:SportBox7.Areas.Editors.Services.HostedServices.BgFootballService.GetBFUThisMonthNews~System.Threading.Tasks.Task{System.Collections.Generic.ICollection{SportBox7.Data.Models.RawArticle}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:SportBox7.Areas.Editors.Controllers.ExternalNewsSourcesController.NewsFeed~Microsoft.AspNetCore.Mvc.IActionResult")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "<Pending>", Scope = "member", Target = "~M:SportBox7.Areas.Editors.Services.Interfaces.EditorService.AddNewDraft(SportBox7.Areas.Editors.ViewModels.AddArticleViewModel)")]
